package es.upm.dit.isst.ioh_api;

// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

public class HoststatsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void hoststats() {
    driver.get("http://localhost:5173/register");
    driver.manage().window().setSize(new Dimension(1084, 786));
    driver.findElement(By.cssSelector(".\\_loginLink_hgvn8_113")).click();
    driver.findElement(By.id("host-login-button")).click();
    {
      WebElement element = driver.findElement(By.id("host-login-button-confirm"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".\\_loginForm_hgvn8_213")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("host@host.com");
    driver.findElement(By.name("password")).sendKeys("1234");
    driver.findElement(By.id("host-login-button-confirm")).click();
    driver.findElement(By.id("menu-hamburguesa")).click();
    driver.findElement(By.cssSelector("#menu-historial-accesos > span")).click();

    // 1) Esperar a que la tabla de estadísticas (logs) sea visible
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("events-table")));

    driver.findElement(By.id("download-csv-button")).click();
  }
}
