// Generated by Selenium IDE

package es.upm.dit.isst.ioh_api;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import static org.junit.jupiter.api.Assertions.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Usersmoketest01PRUEBASTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void usersmoketest01PRUEBAS() {
    driver.get("http://localhost:5173/register");
    driver.manage().window().setSize(new Dimension(640, 807));
    driver.findElement(By.cssSelector(".\\_loginLink_1o6nq_111")).click();
    driver.findElement(By.cssSelector(".\\_clientButton_1o6nq_175")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("user@user.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".\\_loginButton_1o6nq_243")).click();
    driver.findElement(By.cssSelector(".\\_configureButton_1y70k_215")).click();
    driver.findElement(By.cssSelector(".\\_hamburgerIcon_1wq2n_95 > path")).click();
    driver.findElement(By.cssSelector(".\\_menuItem2_1wq2n_71")).click();
    driver.findElement(By.cssSelector(".\\_background_1o6nq_311")).click();
  }
}
