package es.upm.dit.isst.ioh_api;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class UserTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void userregisteropenaccess() {
    driver.get("http://localhost:5173/register");
    driver.manage().window().setSize(new Dimension(1315, 762));
    driver.findElement(By.id("register-button")).click();
    driver.findElement(By.id("user-register-button")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("cliente@gmail.com");
    driver.findElement(By.name("password")).sendKeys("1234");
    driver.findElement(By.id("user-register-button-confirm")).click();
    driver.findElement(By.id("open-button-1")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.textToBe(By.id("status-text	"), "🔒 Cerrada"));
    }
    driver.findElement(By.id("open-lock-button")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.textToBe(By.id("status-text	"), "🔓 Abierta"));
    }
    driver.findElement(By.id("menu-hamburguesa")).click();
    driver.findElement(By.cssSelector("span:nth-child(2)")).click();
  }
}
