package es.upm.dit.isst.ioh_api;

// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.time.Duration;

public class UserTest {
  private WebDriver driver;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver(); // Or new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }

  @AfterEach
  public void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  @Test
  public void userregisteropenaccess() {
    driver.get("http://localhost:5173/register");
    driver.manage().window().setSize(new Dimension(1315, 762));
    driver.findElement(By.id("register-button")).click();
    driver.findElement(By.id("user-register-button")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("cliente@gmail.com");
    driver.findElement(By.name("password")).sendKeys("1234");
    driver.findElement(By.id("user-register-button-confirm")).click();

    driver.findElement(By.id("open-button-1")).click();

    /*
     * Este código espera a que el texto del elemento con id "status-text" sea
     * "Estado actual: 🔒 Cerrada".
     */

    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.textToBe(By.id("status-text"), "Estado actual: 🔒 Cerrada"));
    }

    // Una vez que el texto es "Estado actual: 🔒 Cerrada", se hace clic en el botón
    driver.findElement(By.id("open-lock-button")).click();

    /*
     * Este código espera a que el texto del elemento con id "status-text" sea
     * "Estado actual: 🔓 Abierta". Como el polling que se hace a la API de Seam es
     * de 60 segundos,
     * el tiempo de espera se ha aumentado a 70 segundos.
     */
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(70));
      wait.until(ExpectedConditions.textToBe(By.id("status-text"), "Estado actual: 🔓 Abierta"));
    }

    // Cerrar sesión
    driver.findElement(By.id("menu-hamburguesa")).click();
    driver.findElement(By.cssSelector("span:nth-child(2)")).click();
  }
}
